# code: language=ansible
---
- name: Add qdrant group
  ansible.builtin.group:
    name: "{{ qdrant_group }}"
    system: true
- name: Add qdrant user
  ansible.builtin.user:
    name: "{{ qdrant_user }}"
    group: "{{ qdrant_group }}"
    system: true
- name: Create qdrant directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ qdrant_user }}"
    group: "{{ qdrant_group }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ qdrant_root }}"
    - "{{ (qdrant_root + '/' + storage.storage_path | default('./storage')) | realpath }}"
    - "{{ (qdrant_root + '/' + storage.snapshots_path | default('./snapshots')) | realpath }}"
