# code: language=ansible
---
- name: Verify
  hosts: all
  gather_facts: false
  become: true
  tasks:
    ## テストの前処理
    - name: Gather package facts
      ansible.builtin.package_facts:
    - name: Gather service facts
      ansible.builtin.service_facts:
    - name: Gather listen ports facts
      community.general.listen_ports_facts:
    - name: Set listen port variables
      ansible.builtin.set_fact:
        listen_tcp_posts: "{{ ansible_facts.tcp_listen | map(attribute='port') | unique | sort | list }}"
        listen_udp_posts: "{{ ansible_facts.udp_listen | map(attribute='port') | unique | sort | list }}"
    ## パッケージのテスト
    - name: Assert package
      ansible.builtin.assert:
        that:
          - ansible_facts.packages['qdrant'] is defined
    ## ユーザーのテスト
    - name: Test user
      block:
        - name: Check user
          ansible.builtin.user:
            name: qdrant
            system: true
          check_mode: true
          register: user_result
        - name: Assert user
          ansible.builtin.assert:
            that:
              - user_result is not changed
    ## グループのテスト
    - name: Test group
      block:
        - name: Check group
          ansible.builtin.group:
            name: qdrant
            system: true
          check_mode: true
          register: group_result
        - name: Assert group
          ansible.builtin.assert:
            that:
              - group_result is not changed
    ## ファイルのテスト
    - name: Test directory
      block:
        - name: Check qdrant root directory
          ansible.builtin.stat:
            path: /opt/qdrant
          register: root_dir_result
        - name: Assert root directory
          ansible.builtin.assert:
            that:
              - root_dir_result.stat.exists
              - root_dir_result.stat.isdir
              - root_dir_result.stat.mode == '0755'
              - root_dir_result.stat.pw_name == 'qdrant'
              - root_dir_result.stat.gr_name == 'qdrant'
        - name: Check qdrant storage directory
          ansible.builtin.stat:
            path: /opt/qdrant/storage
          register: storage_dir_result
        - name: Assert storage directory
          ansible.builtin.assert:
            that:
              - storage_dir_result.stat.exists
              - storage_dir_result.stat.isdir
              - storage_dir_result.stat.mode == '0755'
              - storage_dir_result.stat.pw_name == 'qdrant'
              - storage_dir_result.stat.gr_name == 'qdrant'
        - name: Check qdrant snapshots directory
          ansible.builtin.stat:
            path: /opt/qdrant/snapshots
          register: snapshots_dir_result
        - name: Assert snapshots directory
          ansible.builtin.assert:
            that:
              - snapshots_dir_result.stat.exists
              - snapshots_dir_result.stat.isdir
              - snapshots_dir_result.stat.mode == '0755'
              - snapshots_dir_result.stat.pw_name == 'qdrant'
              - snapshots_dir_result.stat.gr_name == 'qdrant'
    ## サービスのテスト
    - name: Assert service
      ansible.builtin.assert:
        that:
          - ansible_facts.services['qdrant.service'] is defined
          - ansible_facts.services['qdrant.service']['state'] == 'running'
          - ansible_facts.services['qdrant.service']['status'] == 'enabled'
    ## 待受ポートのテスト
    - name: Assert listen port
      ansible.builtin.assert:
        that:
          - 6333 in listen_tcp_posts
          - 6334 in listen_tcp_posts
