# code: language=ansible
---
- name: Create/update systemd unit file
  ansible.builtin.template:
    src: qdrant.service.j2
    dest: /lib/systemd/system/qdrant.service
    mode: "0644"
  notify: restart qdrant
- name: Service qdrant is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: qdrant
    state: started
    enabled: true
# - name: allow qdrant port
#   community.general.ufw:
#     rule: allow
#     port: "123456"
