# code: language=ansible
---
- name: Set Install version variable
  when: qdrant_version == 'latest'
  block:
    - name: Set Github API request header
      ansible.builtin.set_fact:
        github_api_request_headers:
          Accept: application/vnd.github+json
    - name: Merge Github API Authorization request header
      ansible.builtin.set_fact:
        github_api_request_headers: "{{ github_api_request_headers | combine(merge_request_header) }}"
      vars:
        merge_request_header:
          Authorization: Bearer {{ lookup('env', 'GITHUB_TOKEN') }}
      when: lookup('env', 'GITHUB_TOKEN') | length > 0
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ qdrant_repo }}/releases/latest
        headers: "{{ github_api_request_headers }}"
      register: latest_releases
    - name: Set package version variable
      ansible.builtin.set_fact:
        qdrant_version: "{{ latest_releases.json.tag_name }}"
- name: Set asset file variable
  ansible.builtin.set_fact:
    asset_file: qdrant_{{ qdrant_version[1:] }}-1_{{ arch_type_maps[ansible_facts['architecture']] }}.deb
  vars:
    arch_type_maps:
      x86_64: amd64
- name: Install qdrant
  ansible.builtin.apt:
    deb: https://github.com/{{ qdrant_repo }}/releases/download/{{ qdrant_version }}/{{ asset_file }}
